version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  app:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    environment:
      - PGHOST=db
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: 'python app.py'
